/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 736f1944bd4f967ae407b4aa12cb81b1)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
